### ISSUE TITLE
How is this repo related to HoTT/HoTT-Agda?

### ISSUE THREAD

**Issue by langston-barrett** [pcapriotti/agda-base#6]
I was looking at this repo, [favonia/homotopy](https://github.com/favonia/homotopy), and [HoTT/HoTT-Agda](https://github.com/hott/hott-agda/). It seems that the former has been merged into the latter, is that true of this repo as well? 

If so, would you mind marking it in the description and README?

If not, could you please outline the differences/further work done here in the README?

**Comment by pcapriotti** [comment]
No, this is a separate project. I'm not familiar enough with HoTT-Agda to make a list of the differences. Certainly, agda-base doesn't have almost any synthetic homotopy.  It's really just a simple base library that one can use as a starting point for formalising results based on HoTT conventions (i.e. no UIP, univalence, maybe HITs, etc...).
